# Generated by Django 4.0 on 2025-11-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_courseparticipant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseparticipant',
            name='role',
            field=models.CharField(choices=[('participant', 'Peserta'), ('trainer', 'Instruktur'), ('assessor', 'Asesor')], default='participant', max_length=20),
        ),
    ]
