# Generated by Django 4.0 on 2025-11-17 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_rename_is_required_question_required_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='title',
            new_name='exam_title',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='task_title',
        ),
    ]
