# Generated by Django 4.0 on 2025-11-18 07:20

from django.db import migrations, models
import exam.models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_rename_title_exam_exam_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='token',
            field=models.CharField(default=exam.models.Exam.generate_exam_token, editable=False, max_length=6, unique=True),
        ),
    ]
