# Generated by Django 4.0 on 2025-11-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_course_is_active_coursematerial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesyllabus',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coursesyllabus',
            name='informant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coursesyllabus',
            name='sub_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
