# Generated by Django 4.0 on 2025-11-25 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('exam', '0006_courserequirementtemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserequirementsubmission',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courserequirementsubmission',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirement_reviews', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='courserequirementsubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='courserequirementtemplate',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('file', 'File Upload'), ('select', 'Select')], max_length=20),
        ),
    ]
