# Generated by Django 4.0 on 2025-11-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_courserequirementsubmission_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
