# Generated by Django 4.0 on 2025-11-29 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_courseassessment_courseassessmentcriteria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='parent_choice',
            field=models.ForeignKey(blank=True, help_text='Choice pada parent_question yang akan memicu question ini muncul.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_questions', to='exam.choice'),
        ),
        migrations.AddField(
            model_name='question',
            name='parent_question',
            field=models.ForeignKey(blank=True, help_text='Jika diisi, pertanyaan ini muncul hanya ketika parent_choice dipilih.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_questions', to='exam.question'),
        ),
    ]
