# Generated by Django 4.0 on 2025-11-17 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriKeahlian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='KeahlianMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.kategorikeahlian')),
            ],
        ),
        migrations.CreateModel(
            name='Sertifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('penerbit', models.CharField(max_length=255)),
                ('tanggal_terbit', models.DateField()),
                ('tanggal_kadaluarsa', models.DateField(blank=True, null=True)),
                ('file_sertifikat', models.FileField(upload_to='sertifikat/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='PengalamanKerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_perusahaan', models.CharField(max_length=255)),
                ('jabatan', models.CharField(max_length=255)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Pendidikan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenjang', models.CharField(choices=[('SLTP', 'SLTP'), ('SLTA', 'SLTA'), ('S1', 'S1'), ('Profesi', 'Profesi'), ('S2', 'S2'), ('Sp1', 'Sp1'), ('S3', 'S3'), ('Sp2', 'Sp2')], max_length=20)),
                ('nama_pt', models.CharField(max_length=255, verbose_name='Nama Perguruan Tinggi')),
                ('program_studi', models.CharField(max_length=255)),
                ('tahun_masuk', models.PositiveIntegerField()),
                ('tahun_lulus', models.PositiveIntegerField()),
                ('ipk', models.DecimalField(decimal_places=2, max_digits=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Linkedin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_url', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='KeahlianUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keahlian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.keahlianmaster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Identitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=255)),
                ('gelar_depan', models.CharField(blank=True, max_length=50, null=True)),
                ('gelar_belakang', models.CharField(blank=True, max_length=50, null=True)),
                ('tanggal_lahir', models.DateField()),
                ('tempat_lahir', models.CharField(max_length=255)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-Laki'), ('P', 'Perempuan')], max_length=1)),
                ('agama', models.CharField(choices=[('islam', 'Islam'), ('kristen_protestan', 'Kristen Protestan'), ('katolik', 'Katolik'), ('hindu', 'Hindu'), ('buddha', 'Buddha'), ('konghucu', 'Konghucu')], max_length=30)),
                ('nomor_telepon', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
