# Generated by Django 4.0 on 2025-11-17 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('issuer', models.CharField(max_length=255)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='certificates/')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('SLTP', 'SLTP'), ('SLTA', 'SLTA'), ('S1', 'S1'), ('Profesi', 'Profesi'), ('S2', 'S2'), ('Sp1', 'Sp1'), ('S3', 'S3'), ('Sp2', 'Sp2')], max_length=20)),
                ('institution', models.CharField(max_length=255)),
                ('program', models.CharField(blank=True, max_length=255, null=True)),
                ('year_in', models.PositiveIntegerField(blank=True, null=True)),
                ('year_out', models.PositiveIntegerField(blank=True, null=True)),
                ('gpa', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('title_prefix', models.CharField(blank=True, max_length=50, null=True)),
                ('title_suffix', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(choices=[('M', 'Laki-laki'), ('F', 'Perempuan')], max_length=10)),
                ('religion', models.CharField(choices=[('Islam', 'Islam'), ('Kristen Protestan', 'Kristen Protestan'), ('Katolik', 'Katolik'), ('Hindu', 'Hindu'), ('Buddha', 'Buddha'), ('Konghucu', 'Konghucu')], max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='cv.userprofile')),
            ],
        ),
        migrations.RemoveField(
            model_name='keahlianmaster',
            name='kategori',
        ),
        migrations.RemoveField(
            model_name='keahlianuser',
            name='keahlian',
        ),
        migrations.RemoveField(
            model_name='keahlianuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='linkedin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pendidikan',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pengalamankerja',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sertifikasi',
            name='user',
        ),
        migrations.DeleteModel(
            name='Identitas',
        ),
        migrations.DeleteModel(
            name='KategoriKeahlian',
        ),
        migrations.DeleteModel(
            name='KeahlianMaster',
        ),
        migrations.DeleteModel(
            name='KeahlianUser',
        ),
        migrations.DeleteModel(
            name='Linkedin',
        ),
        migrations.DeleteModel(
            name='Pendidikan',
        ),
        migrations.DeleteModel(
            name='PengalamanKerja',
        ),
        migrations.DeleteModel(
            name='Sertifikasi',
        ),
        migrations.AddField(
            model_name='skill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='cv.userprofile'),
        ),
        migrations.AddField(
            model_name='education',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='cv.userprofile'),
        ),
        migrations.AddField(
            model_name='certification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='cv.userprofile'),
        ),
    ]
