# Generated by Django 4.0 on 2025-11-19 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_certification_education_skill_userprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.CharField(choices=[('Basic', 'Dasar'), ('Intermediate', 'Menengah'), ('Advanced', 'Mahir'), ('Expert', 'Ahli')], default='Basic', max_length=20),
        ),
        migrations.CreateModel(
            name='TrainingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('organizer', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='training_certificates/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='cv.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
                ('proficiency', models.CharField(choices=[('Basic', 'Pemula'), ('Intermediate', 'Menengah'), ('Advanced', 'Mahir'), ('Fluent', 'Fasih'), ('Native', 'Penutur Asli')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='cv.userprofile')),
            ],
        ),
    ]
