# Generated by Django 4.0 on 2025-11-19 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_skill_level_traininghistory_languageskill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='institution',
            new_name='institution_name',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='program',
            new_name='study_program',
        ),
    ]
