# Generated by Django 4.0 on 2025-11-19 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_rename_institution_education_institution_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workexperience',
            old_name='company',
            new_name='company_name',
        ),
    ]
