# Generated by Django 4.0 on 2025-11-19 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_rename_company_workexperience_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='name',
            new_name='skill_name',
        ),
    ]
