# Generated by Django 4.0 on 2025-11-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_rename_name_skill_skill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininghistory',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
