# Generated by Django 4.0 on 2025-11-25 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cv', '0007_alter_traininghistory_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(blank=True, max_length=50, null=True)),
                ('nik', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_kerja', models.CharField(blank=True, max_length=255, null=True)),
                ('bidang_kerja', models.CharField(blank=True, max_length=255, null=True)),
                ('jabatan', models.CharField(blank=True, max_length=255, null=True)),
                ('golongan_ruang', models.CharField(blank=True, max_length=50, null=True)),
                ('status_kepegawaian', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
